Intwenty/Controllers/ModelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Intwenty.Model.Design;
using Intwenty.Model;
using Microsoft.AspNetCore.Authorization;
using Intwenty.Model.Dto;
using Intwenty.Entity;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using System.IO;
using System.Text;
using Intwenty.Interface;
using Intwenty.Areas.Identity.Models;

namespace Intwenty.Controllers
{

    [ApiExplorerSettings(IgnoreApi = true)]
    [Authorize(Policy = "IntwentyModelAuthorizationPolicy")]
    public class ModelController : Controller
    {
        public IIntwentyDataService DataRepository { get; }
        public IIntwentyModelService ModelRepository { get; }

        public ModelController(IIntwentyDataService ms, IIntwentyModelService sr)
        {
            DataRepository = ms;
            ModelRepository = sr;
        }


        [HttpGet("/Model/ApplicationList")]
        public IActionResult ApplicationList()
        {
            if (!User.Identity.IsAuthenticated)
                return Forbid();
            if (!User.IsInRole(IntwentyRoles.RoleSystemAdmin) && !User.IsInRole(IntwentyRoles.RoleSuperAdmin))
                return Forbid();

            return View();
        }

        [HttpGet("/Model/ApplicationCreate")]
        public IActionResult ApplicationCreate()
        {
            if (!User.Identity.IsAuthenticated)
                return Forbid();
            if (!User.IsInRole(IntwentyRoles.RoleSystemAdmin) && !User.IsInRole(IntwentyRoles.RoleSuperAdmin))
                return Forbid();

            return View();
        }


        [HttpGet("/Model/ApplicationEdit/{applicationid}")]
        public IActionResult ApplicationEdit(int applicationid)
        {
            if (!User.Identity.IsAuthenticated)
                return Forbid();
            if (!User.IsInRole(IntwentyRoles.RoleSystemAdmin) && !User.IsInRole(IntwentyRoles.RoleSuperAdmin))
                return Forbid();

            ViewBag.SystemId = Convert.ToString(applicationid);
            return View();
        }

        [HttpGet("/Model/ApplicationViewList/{applicationid}")]
        public IActionResult ApplicationViewList(int applicationid)
        {
            if (!User.Identity.IsAuthenticated)
                return Forbid();
            if (!User.IsInRole(IntwentyRoles.RoleSystemAdmin) && !User.IsInRole(IntwentyRoles.RoleSuperAdmin))
                return Forbid();

            var model = ModelRepository.GetApplicationModel(applicationid);


            return View(model);
        }

        [HttpGet("/Model/Database/{applicationid}")]
        public IActionResult Database(int applicationid)
        {
            if (!User.Identity.IsAuthenticated)
                return Forbid();
            if (!User.IsInRole(IntwentyRoles.RoleSystemAdmin) && !User.IsInRole(IntwentyRoles.RoleSuperAdmin))
                return Forbid();

            ViewBag.SystemId = Convert.ToString(applicationid);
            return View();
        }






        [HttpGet("/Model/UserInterfaceInputDesign/{applicationid}/{uimetacode}")]
        public IActionResult UserInterfaceInputDesign(int applicationid, string uimetacode)
        {
            if (!User.Identity.IsAuthenticated)
                return Forbid();
            if (!User.IsInRole(IntwentyRoles.RoleSystemAdmin) && !User.IsInRole(IntwentyRoles.RoleSuperAdmin))
                return Forbid();

            var appmodel = ModelRepository.GetApplicationModel(applicationid);
            if (appmodel == null)
                return BadRequest();

            var model = appmodel.GetUserInterface(uimetacode);
            if (model == null)
                return BadRequest();



            return View(model);
        }

        [HttpGet("/Model/UserInterfaceListDesign/{applicationid}/{uimetacode}")]
        public IActionResult UserInterfaceListDesign(int applicationid, string uimetacode)
        {
            if (!User.Identity.IsAuthenticated)
                return Forbid();
            if (!User.IsInRole(IntwentyRoles.RoleSystemAdmin) && !User.IsInRole(IntwentyRoles.RoleSuperAdmin))
                return Forbid();

            var appmodel = ModelRepository.GetApplicationModel(applicationid);
            if (appmodel == null)
                return BadRequest();

            var model = appmodel.GetUserInterface(uimetacode);
            if (model == null)
                return BadRequest();


            return View(model);
        }

        public IActionResult EditModelTranslations()
        {
            if (!User.Identity.IsAuthenticated)
                return Forbid();
            if (!User.IsInRole(IntwentyRoles.RoleSystemAdmin) && !User.IsInRole(IntwentyRoles.RoleSuperAdmin))
                return Forbid();

            return View();
        }

        public IActionResult EditNonModelTranslations()
        {
            if (!User.Identity.IsAuthenticated)
                return Forbid();
            if (!User.IsInRole(IntwentyRoles.RoleSystemAdmin) && !User.IsInRole(IntwentyRoles.RoleSuperAdmin))
                return Forbid();

            return View();
        }

        public IActionResult EditEndpoints()
        {
            if (!User.Identity.IsAuthenticated)
                return Forbid();
            if (!User.IsInRole(IntwentyRoles.RoleSystemAdmin) && !User.IsInRole(IntwentyRoles.RoleSuperAdmin))
                return Forbid();

            return View();
        }


        public IActionResult EditValueDomains()
        {
            if (!User.Identity.IsAuthenticated)
                return Forbid();
            if (!User.IsInRole(IntwentyRoles.RoleSystemAdmin) && !User.IsInRole(IntwentyRoles.RoleSuperAdmin))
                return Forbid();

            return View();
        }

        public IActionResult EventLog(string logname)
        {
            if (!User.Identity.IsAuthenticated)
                return Forbid();
            if (!User.IsInRole(IntwentyRoles.RoleSystemAdmin) && !User.IsInRole(IntwentyRoles.RoleSuperAdmin))
                return Forbid();

            if (string.IsNullOrEmpty(logname))
                logname = "Intwenty";

            ViewBag.LogName = logname;

            return View();
        }

        public IActionResult ToolConfigureDatabase()
        {
            if (!User.Identity.IsAuthenticated)
                return Forbid();
            if (!User.IsInRole(IntwentyRoles.RoleSystemAdmin) && !User.IsInRole(IntwentyRoles.RoleSuperAdmin))
                return Forbid();

            return View();
        }

        public IActionResult ToolValidateModel()
        {
            if (!User.Identity.IsAuthenticated)
                return Forbid();
            if (!User.IsInRole(IntwentyRoles.RoleSystemAdmin) && !User.IsInRole(IntwentyRoles.RoleSuperAdmin))
                return Forbid();

            var res = ModelRepository.ValidateModel();
            return View(res);
        }

        public IActionResult ToolModelDocumentation()
        {
            if (!User.Identity.IsAuthenticated)
                return Forbid();
            if (!User.IsInRole(IntwentyRoles.RoleSystemAdmin) && !User.IsInRole(IntwentyRoles.RoleSuperAdmin))
                return Forbid();

            var client = DataRepository.GetDataClient();
            var dbtypemap = client.GetDbTypeMap();
            var res = new List<ApplicationModel>();
            var appmodels = ModelRepository.GetApplicationModels();
            foreach (var app in appmodels)
            {
                foreach (var col in app.DataStructure.Where(p => p.IsMetaTypeDataColumn))
                {
                    var dbtype = dbtypemap.Find(p => p.IntwentyType == col.DataType && p.DbEngine == client.Database);
                    if (dbtype != null)
                        col.AddUpdateProperty("DBDATATYPE", dbtype.DBMSDataType);
                }
            }
            return View(appmodels);
        }

        public IActionResult ToolCacheMonitor()
        {
            if (!User.Identity.IsAuthenticated)
                return Forbid();
            if (!User.IsInRole(IntwentyRoles.RoleSystemAdmin) && !User.IsInRole(IntwentyRoles.RoleSuperAdmin))
                return Forbid();


            var cachedescription = ModelRepository.GetCachedObjectDescriptions();
            return View(cachedescription);
        }



        public IActionResult ImportModel()
        {
            if (!User.Identity.IsAuthenticated)
                return Forbid();
            if (!User.IsInRole(IntwentyRoles.RoleSuperAdmin))
                return Forbid();

            return View();
        }

        public IActionResult ImportData()
        {
            if (!User.Identity.IsAuthenticated)
                return Forbid();
            if (!User.IsInRole(IntwentyRoles.RoleSuperAdmin))
                return Forbid();

            return View();
        }






    }
}

Intwenty/Views/Shared/_DefaultListView.cshtml
@model Intwenty.Model.UIRendering.UIView

@if (!Model.Columns.Exists(p => p.HasPropertyWithValue("HIDEFILTER", "TRUE")))
{
<div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-3"></div>
    <div class="col-lg-2"></div>
    <div class="col-lg-2">
        <div class="form-group">
            <label class="control-label">Value</label>
            <input type="text" class="form-control form-control-sm" v-model="model.filtervalue" v-on:blur="handleFilterValue" />
        </div>
    </div>
    <div class="col-lg-2">
        <div class="form-group">
            <label class="control-label">Filter</label>
            <select v-model="model.filterfield" class="form-control form-control-sm">
                @{
                    foreach (var c in Model.Columns)
                    {
                        <option value="@c.DataColumnDbName">@c.Title</option>
                    }
                }
            </select>
        </div>
    </div>
</div>
}



<table class="table table-responsive-sm">
    <thead>
        <tr>
            <th style="width:5%"></th>
            <th style="width:5%"></th>
            @{
                foreach (var c in Model.Columns)
                {
                    <th v-on:click="sortBycolumn('@c.DataColumnDbName')" style="cursor:pointer">@c.Title <span class="fa fa-sort-alpha-down-alt"></span></th>

                }
            }
        </tr>
    </thead>
    <tr v-for="item in sortedResults">
        <td style="vertical-align:middle"><button class="btn btn-sm btn-danger" v-on:click="deleteApplication(item)"><span class="fas fa-trash" title="Remove"></span></button></td>
        <td style="vertical-align:middle"><a v-bind:href="'/Application/Edit/@Model.ApplicationId/' + item.Id" class="btn btn-sm btn-secondary" role="button"><span class="fas fa-edit" title="Edit"></span></a></td>
        @{
            foreach (var c in Model.Columns)
            {

                if (c.IsMetaTypeImage)
                {
                    <td>
                        <img v-bind:src="item.@c.DataColumnDbName" width="80" class="rounded" />
                    </td>
                }
                else
                {
                    <td>{{item.@c.DataColumnDbName}}</td>
                }
             }

         }
        
    </tr>

</table>
<nav>
    <ul class="pagination">
        <li class="page-item" v-bind:class="{ disabled: isFirstPage }"><a class="page-link" href="#" v-on:click="prevpage()">Previous {{listRetrieveInfo.batchSize}}</a></li>
        <li class="page-item"><a class="page-link" href="#" v-on:click="nextpage()">Next {{listRetrieveInfo.batchSize}}</a></li>
    </ul>
</nav>

Intwenty/Views/Shared/_IntwentyAPIMenu.cshtml
@if (Settings.Value.APIEnable)
{
    <li class="nav-item dropdown">
        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true"><span class="nav-label"><span class="fas fa-handshake"></span> Integrations</span> <span class="caret"></span></a>
        <div class="dropdown-menu">



            @if (User.IsInRole(IntwentyRoles.RoleSuperAdmin) || User.IsInRole(IntwentyRoles.RoleSystemAdmin))
            {
                <a class="dropdown-item" asp-controller="Model" asp-action="EditEndpoints"><span class="fas fa-handshake"></span> API Management</a>
            }


            @if (User.IsInRole("SUPERADMIN") || User.IsInRole("SYSTEMADMIN") || User.IsInRole("APIUSER"))
            {
                <a class="dropdown-item" href="~/swagger/index.html" target="_blank"><span class="fas fa-handshake"></span> API Docs and Testing</a>
            }

        </div>
    </li>

}

Intwenty/Views/Shared/_IntwentyAdminMenu.cshtml
<li class="nav-item dropdown">
    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true"><span class="nav-label"><span class="fa fa-cog"></span> Administration</span> <span class="caret"></span></a>
    <div class="dropdown-menu">


        @if (User.IsInRole("SUPERADMIN") || User.IsInRole("SYSTEMADMIN"))
        {
            <a class="dropdown-item" asp-controller="Model" asp-action="ApplicationList"><span class="fa fa-cogs"></span> Manage applications</a>
            <a class="dropdown-item" asp-controller="Model" asp-action="ToolConfigureDatabase"><span class="fa fa-cogs"></span> Configure database</a>
            <a class="dropdown-item" asp-controller="Model" asp-action="EditValueDomains"><span class="fa fa-database"></span> Value domains</a>


            <div class="dropdown-divider"></div>

            <a class="dropdown-item" asp-controller="Model" asp-action="ToolValidateModel"><span class="fa fa-info"></span> Validate model</a>
            <a class="dropdown-item" asp-controller="Model" asp-action="ToolModelDocumentation"><span class="fa fa-book"></span> Model documentation</a>
            <a class="dropdown-item" asp-controller="SystemTest" asp-action="RunTests"><span class="fa fa-cogs"></span> Run System Tests</a>
            <a class="dropdown-item" asp-controller="Model" asp-action="ToolCacheMonitor"><span class="fa fa-cogs"></span> Cache Monitor</a>
            <a class="dropdown-item" asp-controller="Model" asp-action="EventLog" asp-route-logname="Intwenty"><span class="fa fa-cogs"></span> Logviewer</a>



            @if (User.IsInRole("SUPERADMIN"))
            {
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" asp-controller="ModelAPI" asp-action="ExportJsonModel"><span class="fa fa-cogs"></span> Export Model (json)</a>
                <a class="dropdown-item" asp-controller="ModelAPI" asp-action="ExportCSharpModel"><span class="fa fa-cogs"></span> Export Model (C#)</a>
                <a class="dropdown-item" asp-controller="ModelAPI" asp-action="ExportSqlModel"><span class="fa fa-cogs"></span> Export Model (SQL)</a>
                <a class="dropdown-item" asp-controller="ModelAPI" asp-action="ExportXmlModel"><span class="fa fa-cogs"></span> Export Model (Xml)</a>
                <a class="dropdown-item" asp-controller="Model" asp-action="ImportModel"><span class="fa fa-cogs"></span> Import Model</a>
                <a class="dropdown-item" asp-controller="ModelAPI" asp-action="ExportData"><span class="fa fa-cogs"></span> Export Data</a>
                <a class="dropdown-item" asp-controller="Model" asp-action="ImportData"><span class="fa fa-cogs"></span> Import Data</a>
            }



            <div class="dropdown-divider"></div>

            <a class="dropdown-item" asp-controller="Model" asp-action="EditModelTranslations"><span class="fas fa-globe-europe"></span> Model Localization</a>
            <a class="dropdown-item" asp-controller="Model" asp-action="EditNonModelTranslations"><span class="fas fa-globe-europe"></span> Localization Keys</a>
        }


    </div>
</li>

Intwenty/Views/Shared/_IntwentyAppMenu.cshtml
@{

    var systems = new List<SystemModelItem>();
    var views = await ModelRepository.GetApplicationMenuAsync(User);
    foreach (var a in views)
    {
        if (!systems.Exists(p => p.MetaCode == a.SystemMetaCode))
        {
            if (a.SystemInfo != null && views.Exists(p=> p.SystemMetaCode == a.SystemMetaCode))
            {
                systems.Add(a.SystemInfo);
            }
        }
    }

}





<li class="nav-item dropdown">
    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true"><span class="nav-label"><span class="fa fa-table"></span> @Localizer["Menu"]</span> <span class="caret"></span></a>
    <div class="dropdown-menu">
        @{



            var cnt = 0;
            foreach (var sys in systems)
            {
                if (cnt > 0)
                {
                    <div class="dropdown-divider"></div>
                }
                <div class="dropdown-item"><strong>@sys.Title</strong></div>
                <div class="dropdown-divider"></div>

                foreach (var view in views.Where(p => p.SystemMetaCode == sys.MetaCode && !p.Path.Contains("{id}")))
                {
                    var path = view.Path;
                    var reqinfo = string.Format("VIEWID={0}", view.Id);
                    path = "~"+path.Replace("{requestinfo}", reqinfo.B64UrlEncode());
                    <a class="dropdown-item" href="@Url.Content(path)">@view.LocalizedTitle</a>
                }

                cnt++;
            }

        }


    </div>
</li>

Intwenty/Views/Shared/_IntwentyIdentityAccessMenu.cshtml
<li class="nav-item dropdown">
    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true"><span class="nav-label"><span class="fa fas-users"></span><i class="fa fa-users"></i> Identity Management</span> <span class="caret"></span></a>
    <div class="dropdown-menu">
        <a class="dropdown-item" asp-area="Identity" asp-page="/IAM/UserList"><span class="fas fa-users"></span> Users</a>
        <a class="dropdown-item" asp-area="Identity" asp-page="/IAM/OrganizationList"><span class="fas fa-user"></span> Organizations</a>
        <a class="dropdown-item" asp-area="Identity" asp-page="/IAM/ProductList"><span class="fab fa-product-hunt"></span> Products</a>
        @if (User.IsInRole("SUPERADMIN"))
        {
            <a class="dropdown-item" asp-controller="Model" asp-action="EventLog" asp-route-logname="IAM"><span class="fa fa-cogs"></span> Logviewer</a>
        }
    </div>
</li>

Intwenty/Views/Shared/_MetaAppDescription.cshtml
<h4>Configuration</h4>

<div class="row">
    <div class="col-lg-6">

        <div class="form-group">
            <label class="control-label">System<span style="color: red"> *</span></label>
            <select id="cbSystem" v-model="model.systemMetaCode" class="form-control form-control-sm" :disabled="model.id > 0" v-on:input="setCodes">
                <option v-for="sys in systems" v-bind:value="sys.metaCode">{{sys.title}}</option>
            </select>
        </div>

        <div class="form-group">
            <label class="control-label">Title<span style="color: red"> *</span></label>
            <input id="apptitle" type="text" class="form-control form-control-sm" v-model="model.title" v-on:input="setCodes" />
        </div>

        <div class="form-group">
            <label class="control-label">Description<span style="color: red"> *</span></label>
            <input id="appdescr" type="text" class="form-control form-control-sm" v-model="model.description" />
        </div>

        <div class="form-group">
            <label class="control-label">Database name<span style="color: red"> *</span></label>
            <input id="appdbname" type="text" class="form-control form-control-sm" v-model="model.dbName" :disabled="model.id > 0" />
        </div>

        <div class="form-group">
            <label class="control-label">Code<span style="color: red"> *</span></label>
            <input id="appmetacode" type="text" class="form-control form-control-sm" v-model="model.metaCode" :disabled="model.id > 0" />
        </div>

        <div class="form-group">
            <label class="control-label">Data Mode</label>
            <select id="cbTenantIsolvl" v-model.number="model.dataMode" class="form-control form-control-sm">
                <option value="0">Standard</option>
                <option value="1">Simple</option>
            </select>
        </div>

        <div class="form-group">
            <input id="useversioning" type="checkbox" v-model="model.useVersioning" :disabled="model.id > 0" /> Use Versioning
        </div>

        <div class="form-group">
            <label class="control-label">Tenant Isolation Level</label>
            <select id="cbTenantIsolvl" v-model.number="model.tenantIsolationLevel" class="form-control form-control-sm">
                <option value="0">None</option>
                <option value="1">User</option>
                <option value="2">Organization</option>
            </select>
        </div>

        <div class="form-group">
            <label class="control-label">Tenant Isolation Method</label>
            <select id="cbTenantIsoMet" v-model.number="model.tenantIsolationMethod" class="form-control form-control-sm">
                <option value="0">None</option>
                <option value="1">ByRows</option>
                <option value="2">ByTables</option>
            </select>
        </div>

    </div>
    <div class="col-lg-6">

       

        <div class="alert alert-primary" role="alert">
            <i class="far fa-question-circle"></i>
            <br />
            <br />
            <strong>Data Mode</strong><br />
            <hr />
            <strong>Standard</strong><br />Use all standard features including instance catalog and subtables  <br /><br />
            <strong>Simple</strong><br />Use this mode for performance. Only one table per application is allowed and it is not possible to use versioning or other features <br /><br />
            <br />
            <br />
            <strong>Versioning</strong><br />
            <hr />
            If versioning is applied, database updates will generate new versions (inserts) of rows rather than updating them.
            <br />
            <br />
            <strong>Tenant Isolation</strong><br />
            <hr />
            <strong>None</strong><br />All data is accessible to all authorized users <br /><br />
            <strong>User</strong><br />Authorized users are limited to access their own data <br /><br />
            <strong>Organization</strong><br />Authorized users can access all data that is owned by the user's organization<br /><br />
            <br />
            <strong>Tenant Isolation Method</strong><br />
            <hr />
            <strong style="width:100px">None: </strong> None <br />
            <strong style="width:100px">ByRows: </strong> Tenants use the same tables <br />
            <strong style="width:100px">ByTables: </strong> Tenants store the data in their own tables
        </div>
    </div>
</div>

Intwenty/Views/Shared/_Modals.cshtml
<div class="modal" id="msg_dlg_modal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 id="msg_dlg_modal_hdr" class="modal-title">Information</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p id="msg_dlg_modal_text"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal" id="msg_dlg_modal_closebtn">Close</button>
            </div>
        </div>
    </div>
</div>


<div class="modal" id="yesno_dlg_modal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 id="yesno_dlg_modal_hdr" class="modal-title">Information</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p id="yesno_dlg_modal_text"></p>
            </div>
            <div class="modal-footer">
                <button id="yesno_dlg_modal_yesbtn" type="button" class="btn btn-sm btn-primary" data-dismiss="modal">Yes</button>
                <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>





<div class="modal" id="property_dlg_modal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 id="property_dlg_modal_hdr" class="modal-title">Properties</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="property_dlg_modal_body">
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

Intwenty/Views/Shared/_PropertyUI.cshtml
@model string 

<!--

Requires an item with properties, which name is passed as the model  

-->


<div>

    <hr />

    <div class="form-inline" v-if="@(Model).currentProperty">

        <div class="mr-2">
            <select id="propcbox"
                    name="propcbox"
                    v-model="@(Model).currentProperty"
                    v-on:change="propertyChanged(event)"
                    class="form-control form-control-sm">
                <option v-for="item in selectableProperties(@(Model))" v-bind:value="item">{{item.displayName}}</option>
            </select>
        </div>

        <div class="mr-2" v-if="@(Model).currentProperty.isBoolType">

        </div>

        <div class="mr-2" v-if="@(Model).currentProperty.isStringType">
            <input class="form-control-sm" v-model="@(Model).currentProperty.codeValue" type="text" />
        </div>

        <div class="mr-2" v-if="@(Model).currentProperty.isNumericType">
            <input class="form-control-sm" v-model="@(Model).currentProperty.codeValue" type="number" />
        </div>

        <div class="mr-2" v-if="@(Model).currentProperty.isListType">
            <div class="form-group">
                <select id="cboxpropvalues"
                        name="cboxpropvalues"
                        v-model="@(Model).currentProperty.codeValue"
                        class="form-control form-control-sm">
                    <option v-for="item in @(Model).currentProperty.validValues" v-bind:value="item.codeValue">{{item.displayValue}}</option>
                </select>
            </div>
        </div>


        <button class="btn btn-sm btn-secondary mr-2" v-on:click="addProperty(@(Model))" style="margin-left:2px"><span class="fa fa-plus"></span> Add</button>


    </div>

    <hr />

    <table class="table table-sm" style="width:90%">
        <thead>
            <tr>
                <th>Property</th>
                <th>Value</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr v-for="property in @(Model).propertyList">
                <td>{{property.codeName}}</td>
                <td>{{property.displayValue}}</td>
                <td><span v-on:click="deleteProperty(property,@(Model))" class="fa fa-trash" style="cursor:pointer"></span></td>
            </tr>
        </tbody>
    </table>
</div>